sudo: false
dist: trusty
git:
  depth: 20000 # We're cloning a max of xxx commits, so the author date is correct
language: node_js
env:
  global:
    - GET_ENV_VAR=./_scripts/get_env.sh
    - GOPATH="${HOME}/.go_workspace"
    - HUGO_ENV=$($GET_ENV_VAR)
    - HUGO_VERSION=0.31.1
      before_install:
  - export PATH=$HOME:$PATH
  - export HUGO_PACKAGE=hugo_${HUGO_VERSION}_Linux-64bit
  - travis_retry curl -L https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/$HUGO_PACKAGE.tar.gz | tar xz
  - chmod +x ./hugo
  - mv ./hugo $HOME/bin/hugo
install:
  - rm -rf _site
  - yarn install
before_deploy:
  - export PATH=$HOME:$PATH
  - travis_retry curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip -q awscliv2.zip
  - sudo ./aws/install
  - ./_scripts/algolia.sh
# Algolia must be before deploy as AWS is renaming all the .html files which the script expects#
script:
  - ./node_modules/.bin/gulp build
cache:
  yarn: true
  #directories:
  #  - node_modules
branches:
  only:
    - master
    - development
deploy:
  - provider: script
    script:
      - ./_scripts/deploy.sh
    skip_cleanup: true
    on:
      branch:
        - master
        - development
after_deploy:
# Algolia was here before we deployed to AWS
